### ISSUE TITLE
message receive issue

### ISSUE THREAD

**Issue by SagarRaiyani** [Pirngruber/AndroidIM#14]
one message send is successfully receive in other device, but multiple message send at a time the last message print multiple time. Plz solve this issue and reply.......

**Comment by rahulbambale** [comment]
Plz bro tell me whats server use.because use xampp server,when start apk than logcat display the "android im init cant open zip file.plz plz bro help me

**Comment by rahulbambale** [comment]
which online server use plz tell me.

**Comment by Pirngruber** [comment]
fixed
