### ISSUE TITLE
AndroidIM APK does not work

### ISSUE THREAD

**Issue by nhu2000** [Pirngruber/AndroidIM#16]
When I use AndroidIM.apk from GitHub to android phone. Both Login and Signup do not work. But When downloading it directly from Play Store. It works fine. Do I missed anything?

Andrew
Thanks

**Comment by rahulbambale** [comment]
i setup database in xampp server.than open apk file and sign up succesfully,but when i login its said username and password not match.plz help me sir

**Comment by nhu2000** [comment]
I only work for Parse server at moment.

**Comment by Pirngruber** [comment]
deprecated mysql fixed now
