### ISSUE TITLE
server ip address

### ISSUE THREAD

**Issue by shahaf94** [Pirngruber/AndroidIM#17]
I changed the socketoperator class to my wireless network connection ip:
 24. private static final String AUTHENTICATION_SERVER_ADDRESS = "http://192.168.x.x/android-im/";  
but app still crashes in sign up page

are there any more changes i have to include in order to make it run:
changing my ip to static? port forwarding? or changing some settings on the emulator itself??

**Comment by yobra89** [comment]
Hey I'm as well a lost sheep I put in my wireless ip adress but nothing happens please help... Wonderfull tutorial tho on the whole thing please get bck to me asap nonini89@gmail.com thnx man

**Comment by rahulbambale** [comment]
Unmapable encodeing uft 8 error shiw.how to solve plz bro help me.

**Comment by Pirngruber** [comment]
fixed the webapi now
