### ISSUE TITLE
Sign up and logging problem

### ISSUE THREAD

**Issue by EasonWang01** [Pirngruber/AndroidIM#22]
When I pressed (sign up) it says sign up failed for unknown reason,but I can see user created table in mysql,also some error log in the www folder.
And no matter which char I type in the username and password it always can log in.
Do you know how to solve it?
Thanks

**Comment by vkaadheeshwar** [comment]
I too have same error

**Comment by vkaadheeshwar** [comment]
Wats ur database host name in index.php

**Comment by EasonWang01** [comment]
I using root

**Comment by sonal7989** [comment]
When I pressed (sign up) it says sign up failed for unknown reason.. also checked it manually.. there is no user created in mysql.

**Comment by forever420** [comment]
Ok

**Comment by sikrinick** [comment]
Please, try this:https://github.com/Pirngruber/AndroidIM/issues/25
