### ISSUE TITLE
Should include license information

### ISSUE THREAD

**Issue by talas** [Pirngruber/AndroidIM#23]
Hi, it seems there are no license terms included with the code.

From the google code page it looks like the license was GPLv3.

You can download the GPLv3 license text from https://www.gnu.org/licenses/gpl.txt and put it next to README.md.
For more instructions see: https://www.gnu.org/licenses/gpl-howto.html
, or: https://www.gnu.org/licenses/gpl.html (scroll down to How to Apply These Terms to Your New Programs)

Without license information, further development becomes difficult.

**Comment by Pirngruber** [comment]
found the right license now :D 

*license.txt added
