### ISSUE TITLE
server connectivity error

### ISSUE THREAD

**Issue by vabbiee** [Pirngruber/AndroidIM#24]
i am not able to connect it to the server. i am using xampp server and followed the steps as shown in tutorial, but it says that unable to find 192.168.x.x/android-im/ . 
plz help

**Comment by rahulbambale** [comment]
how to connect xampp server plz tell me bro

**Comment by Pirngruber** [comment]
on www.v-city.at you'll find a youtube tutorial for the server setup ;)
