### ISSUE TITLE
For those who can't register new user.

### ISSUE THREAD

**Issue by sikrinick** [Pirngruber/AndroidIM#25]
The reason is pretty simple:
Android-IM Web API doesn't have any code that creates new tables in database, so you have to create them yourself based on queries, that "index.php" makes through "mysql.class.php".
Queries for table creating are in "android-im.sql" but it is not called from any part of code.

For fixing, just add this to "index.php" right before "switch($action)":

$createUsers = "CREATE TABLE IF NOT EXISTS `users` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(45) NOT NULL DEFAULT '',
  `password` varchar(32) NOT NULL DEFAULT '',
  `email` varchar(45) NOT NULL DEFAULT '',
  `date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `status` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `authenticationTime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `userKey` varchar(32) NOT NULL DEFAULT '',
  `IP` varchar(45) NOT NULL DEFAULT '',
  `port` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Index_2` (`username`),
  KEY `Index_3` (`authenticationTime`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7";
   
$createFriends = "CREATE TABLE IF NOT EXISTS `friends` (
  `Id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `providerId` int(10) unsigned NOT NULL DEFAULT '0',
  `requestId` int(10) unsigned NOT NULL DEFAULT '0',
  `status` binary(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `Index_3` (`providerId`,`requestId`),
  KEY `Index_2` (`providerId`,`requestId`,`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 COMMENT='providerId is the Id of the users who wish to be friend with' AUTO_INCREMENT=7";

$createMessages = "CREATE TABLE IF NOT EXISTS `messages` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `fromuid` int(255) NOT NULL,
  `touid` int(255) NOT NULL,
  `sentdt` datetime NOT NULL,
  `read` tinyint(1) NOT NULL DEFAULT '0',
  `readdt` datetime DEFAULT NULL,
  `messagetext` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=22";

$db->query($createUsers);
$db->query($createFriends);
$db->query($createMessages);

**Comment by rahulbambale** [comment]
i setup database in xampp server.than open apk file and sign up succesfully,but when i login its said username and password not match.apk file open in my mobile not emulator.plz help me sir

**Comment by sikrinick** [comment]
Try to find the reason in log files. Maybe server doesn't return on request. Also, check if the yser actually exist in database.
On 20 Jan 2016 14:11, rahulbambale <notifications@github.com> wrote:i setup database in xampp server.than open apk file and sign up succesfully,but when i login its said username and password not match.apk file open in my mobile not emulator.plz help me sir

**Comment by rahulbambale** [comment]
Log cat messge.init cant open zip file.

So what next step I do.plz tell me bro

**Comment by sikrinick** [comment]
Does your user exist in database?

**Comment by narogg** [comment]
As I recall It can't work on localhost, you have to connect to some php server on the web (or on local network). 

WebAPI:
    There is a folder whose name is "android-im_WEBAPI", copy all files under "android-im" folder to a folder in your web server directory, for instance android-im that can be accessed by http://192.168.7.5/android-im/ (192.168.7.5 is the IP address of 
    computer which runs apache and mysql, use local network IP address instead of using localhost or 127.0.0.1).
    Open the index.php and enter database connectivity parameters such as host, username, password etc. write 
    error_reporting(0) in top of index.php
    Create the tables in mysql database with the included android_im.sql

Android APP:
    set AUTHENTICATION_SERVER_ADDRESS in socketOperator, it must be the address where server folder are located,
    for our example it is http://192.168.7.5/android-im/ (don't use localhost)

**Comment by rahulbambale** [comment]
Plz sir upload full tutorial about configure to androidim to server database .plz sir upload video.plz

**Comment by rahulbambale** [comment]
I use xampp server.but didn't workSent from my Huawei Mobile-------- Original Message --------Subject: Re: [AndroidIM] For those who can't register new user. (#25)From: Goran Mandinić To: Pirngruber/AndroidIM CC: rahulbambale As I recall It can't work on localhost, you have to connect to some php server on the web (or on local network). 

WebAPI:
    There is a folder whose name is "android-im_WEBAPI", copy all files under "android-im" folder to a folder in your web server directory, for instance android-im that can be accessed by http://192.168.7.5/android-im/ (192.168.7.5 is the IP address of 
    computer which runs apache and mysql, use local network IP address instead of using localhost or 127.0.0.1).
    Open the index.php and enter database connectivity parameters such as host, username, password etc. write 
    error_reporting(0) in top of index.php
    Create the tables in mysql database with the included android_im.sql

Android APP:
    set AUTHENTICATION_SERVER_ADDRESS in socketOperator, it must be the address where server folder are located,
    for our example it is http://192.168.7.5/android-im/ (don't use localhost)

**Comment by Pirngruber** [comment]
included in 2954aa073887e15c73e028b50fb4da0d82947bf7 
thx to @sikrinick
