### ISSUE TITLE
Php version used ?

### ISSUE THREAD

**Issue by ziadkiwan** [Pirngruber/AndroidIM#47]
Hello AndroidIM, its a great project i'm wondering what PHP version is being used, thank you!

**Comment by mounareda** [comment]
does the PHP file work , because Im having problem with it , it always show me 0 , and I can't login into the app , I have no problem singinup but I have problem singin in

**Comment by ziadkiwan** [comment]
try PHP version 5

**Comment by mounareda** [comment]
I have found the problem it was in the function isConnected in imService , it always returns null .
And I already use PHP5.

**Comment by ziadkiwan** [comment]
nice i didn't face any problem implementing this actually i even expanded the code, this uses XML i changed it to JSON parsing and many more.

**Comment by mounareda** [comment]
Wow that's nice , I'm steel a student and I took this application to learn from it , I have Android class & I was supposed to explain a chat application how it work and give an example I couldn't do the code all by myself so I took this to give it as an example . it was easy to understand.

Thank you very much for being that nice to answer me thank you soo much .

**Comment by ziadkiwan** [comment]
it's fine at your service!

**Comment by lordcharlx** [comment]
@ ziadkiwan  can you upload your fixed version ?

**Comment by ziadkiwan** [comment]
fixed version of what ?

**Comment by lordcharlx** [comment]
@ziadkiwan  

nice i didn't face any problem implementing this  actually i even expanded the code, this uses XML i changed it to JSON  parsing and many more.
