### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by Pirngruber** [Pirngruber/AndroidIM#6]
doesn't jump back to Login Screen on successful registration

**Comment by r-o-h-a-n** [comment]
hi there... i have the same issue as JulienMcJay.. please help us out

**Comment by 12424642** [comment]
@JulienMcJay @r-o-h-a-n You guys ran into the same error as me. The result variable is null. You have to do a null-check before calling equals. Add if(result != null){ after public void run(){ on the SignUp activity.
